import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Articles from "@/app/articles/Articles";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
        <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <h1 className={`mb-3 text-4xl font-semibold mb-8`}>Wszystkie artykuły</h1>
            <Articles/>
            <div>
                {children}
            </div>
        </main>
        </body>
        </html>
    )
}
